repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: local
    hooks:
      - id: isort
        name: isort
        stages: [commit]
        language: system
        entry: python -m isort
        types: [python]
        exclude: pulse/__init__.py

      - id: black
        name: black
        stages: [commit]
        language: system
        entry: python -m black
        types: [python]
        exclude: pulse/__init__.py

      - id: flake8
        name: flake8
        stages: [commit]
        language: system
        entry: python -m flake8
        types: [python]
        exclude: pulse/__init__.py

      # - id: mypy
      #   name: mypy
      #   stages: [commit]
      #   language: system
      #   entry: python -m mypy
      #   types: [python]
      #   exclude: pulse/__init__.py
      #   pass_filenames: false
