# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2.1

executors:
  fenics-latest:
    docker:
      - image: quay.io/fenicsproject/stable:latest
  fenics-adjoint-latest:
    docker:
      - image: quay.io/dolfinadjoint/pyadjoint:latest
  fenics-2017:
    docker:
      - image: finsberg/fenics2017
  fenics-finsberg:
    docker:
      - image: finsberg/fenics

jobs:
  test:
    parameters:
      fenics:
        type: executor
    executor: << parameters.fenics >>
    steps:
      - checkout

      - restore_cache:
          keys:
            - dolfin-jit-cache-pip

      - run:
          name: install dependencies
          command: |
            python3 -m pip install --upgrade pip
            python3 -m pip install h5py --no-binary=h5py

      - run:
          name: install package
          command: |
            make dev

      # run tests!
      - run:
          name: run tests
          command: |
            python3 -m pytest

      - save_cache:
          key: dolfin-jit-cache-pip
          paths:
            - ~/.cache/instant
            - ~/.cache/dijitso
            - ~/.cache/pip

      - store_artifacts:
          path: htmlcov
          destination: htmlcov

      - run:
          name: codecov
          command: |
            bash <(curl -s https://codecov.io/bash)

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              fenics: [
                  fenics-latest,
                  fenics-2017,
                  fenics-adjoint-latest,
                  # fenics-finsberg,
                ]
          filters:
            branches:
              ignore:
                - gh-pages
