{% set version = "2020.2" %}

package:
  name: pulse
  version: {{ version }}

source:
  url: https://github.com/finsberg/pulse/archive/v{{ version }}.tar.gz
  sha256: 5ef5807bfdf67e74f1de67a519196f4d0d08985d51aa754106c0820e63babf39

build:
  number: 0
  skip: True  # [win or py<36]
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python
    - pip
    - h5py
    - fenics
    - scipy
    - numpy
    - daiquiri
    - matplotlib
  run:
    - python
    - h5py
    - fenics
    - scipy
    - matplotlib
    - numpy
    - daiquiri
test:
  imports:
    - pulse

about:
  home: https://finsberg.github.io/pulse
  license: LGPL-3.0-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: 'pulse is a python library based on FEniCS that aims to solve problems in continuum mechanics'

  description: |
    pulse is a python library based on FEniCS that aims to solve
    problems in continuum mechanics, in particular cardiac mechanics.
  doc_url: https://finsberg.github.io/pulse
  dev_url: https://github.com/finsberg/pulse
extra:
  recipe-maintainers:
    - finsberg
