name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    container:
      image: quay.io/fenicsproject/stable:latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
            docs/_build/jupyter_execute
          key: cache_v2
          restore-keys: |
            cache_v2

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Install gmsh
        run: |
          apt-get update && apt-get install wget libglu1 libxrender1  libxcursor-dev libxft-dev libxinerama-dev -y
          cd /usr/local
          wget -nc  http://gmsh.info/bin/Linux/gmsh-4.6.0-Linux64-sdk.tgz
          tar -xf gmsh-4.6.0-Linux64-sdk.tgz
          rm gmsh-4.6.0-Linux64-sdk.tgz

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt install gmsh -y
          sudo apt install -y pandoc
          make dev

      - name: Build docs
        run: |
          export PYTHONPATH=/usr/local/gmsh-4.6.0-Linux64-sdk/lib:$PYTHONPATH
          export PATH=/usr/local/gmsh-4.6.0-Linux64-sdk/bin:$PATH
          make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
