name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          [
            "finsberg/fenics-extra",
            "finsberg/pyadjoint-extra",
          ]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pulse
            ~/.cache/pip
          key: ${{ matrix.container }}-cache_v9
          restore-keys: |
            ${{ matrix.container }}-cache_v9

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[test,plot,dev]"


      - name: Test with pytest
        uses: nick-invision/retry@v2
        with:
          timeout_minutes: 120
          max_attempts: 5
          retry_on: error
          command: python3 -m pytest
