name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        container:
          [
            "quay.io/fenicsproject/stable:latest",
            "quay.io/dolfinadjoint/pyadjoint:latest",
            "finsberg/fenics2017",
          ]

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pulse
            ~/.cache/pip
          key: ${{ matrix.container }}-cache_v3
          restore-keys: |
            ${{ matrix.container }}-cache_v3

      - name: Install gmsh
        run: |
          apt-get update && apt-get install wget libglu1 libxrender1  libxcursor-dev libxft-dev libxinerama-dev -y
          cd /usr/local
          wget -nc  http://gmsh.info/bin/Linux/gmsh-4.6.0-Linux64-sdk.tgz
          tar -xf gmsh-4.6.0-Linux64-sdk.tgz
          rm gmsh-4.6.0-Linux64-sdk.tgz
          export PYTHONPATH=/usr/local/gmsh-4.6.0-Linux64-sdk/lib:$PYTHONPATH
          export PATH=/usr/local/gmsh-4.6.0-Linux64-sdk/bin:$PATH

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install h5py --no-binary=h5py
          python3 -m pip install -e ".[test,plot,mesh,dev]"

      - name: Run flake8
        run: |
          python3 -m flake8 pulse tests

      - name: Run black
        run: |
          python3 -m black --check pulse tests

      - name: Run mypy
        run: |
          python3 -m mypy pulse tests

      - name: Test with pytest
        run: |
          python3 -m pytest
